#ifndef ESP32_CONTROLLER_DEFS_H
#define ESP32_CONTROLLER_DEFS_H

// LORA TRANSCEIVER PINS
#define LORA_SCK 5
#define LORA_MISO 19
#define LORA_MOSI 27
#define LORA_SS 18
#define LORA_RST 14
#define LORA_DIO0 26

// LORA FREQUENCY BAND
// 433E6 for Asia
// 866E6 for Europe
// 915E6 for North America
#define LORA_BAND 866E6

// LORA SYNCWORD
#define LORA_SYNCWORD 0xCA

// USB SERIAL SPEED
#define SERIAL_BAUDRATE 115200

#endif /* ESP32_CONTROLLER_DEFS_H */