#ifndef GOOSEKA_DEFS_H
#define GOOSEKA_DEFS_H

#define MOTOR_POLES 14  

#define LEFT_PWM_PIN 25
#define LEFT_TELEMETRY_READ_PIN 35
#define LEFT_TELEMETRY_UNUSED_PIN 17

#define RIGHT_PWM_PIN 23
#define RIGHT_TELEMETRY_READ_PIN 34
#define RIGHT_TELEMETRY_UNUSED_PIN 13

#define PWM_MIN 1040
#define PWM_MAX 1960

#define SERIAL_BUFFER_SIZE 10

#endif /* GOOSEKA_DEFS_H */