#ifndef GOOSEKA_DEFS_H
#define GOOSEKA_DEFS_H

// MOTOR PARAMETERS
#define MOTOR_POLES 14  

// ESC PINS
#define LEFT_PWM_PIN 25
#define LEFT_TELEMETRY_READ_PIN 35
#define LEFT_TELEMETRY_UNUSED_PIN 17

#define RIGHT_PWM_PIN 23
#define RIGHT_TELEMETRY_READ_PIN 34
#define RIGHT_TELEMETRY_UNUSED_PIN 13

// ESC PWM CONFIGURATION
#define PWM_MIN 1040
#define PWM_MAX 1960

// TELEMETRY SERIAL BUFFER
#define SERIAL_BUFFER_SIZE 10

// LORA TRANSCEIVER PINS
#define LORA_SCK 5
#define LORA_MISO 19
#define LORA_MOSI 27
#define LORA_SS 18
#define LORA_RST 14
#define LORA_DIO0 26

// LORA FREQUENCY BAND
// 433E6 for Asia
// 866E6 for Europe
// 915E6 for North America
#define LORA_BAND 866E6

// LORA SYNCWORD
#define LORA_SYNCWORD 0xCA

#endif /* GOOSEKA_DEFS_H */